image:
  repository: otel/opentelemetry-collector-contrib
  tag: latest
  pullPolicy: IfNotPresent

mode: deployment

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:
    otlp/tempo:
      endpoint: "tempo:4317"
      tls:
        insecure: true

  extensions:
    health_check:
      endpoint: ${env:MY_POD_IP}:13133

  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlp/tempo]

service:
  enabled: true
  type: ClusterIP