alloy:
  extraVolumeMounts:
    - name: varlog
      mountPath: /var/log
  extraVolumes:
    - name: varlog
      hostPath:
        path: /var/log

  logs:
    enabled: true
    positions:
      enabled: true
    configs:
      - name: logs-to-loki
        clients:
          - url: "http://loki:3100/loki/api/v1/push"
        scrape_configs:
          - job_name: kubernetes-containers
            static_configs:
              - targets: []
                labels:
                  job: kubernetes-containers
                  __path__: /var/log/containers/*.log
            pipeline_stages:
              - cri: {}
